### ISSUE TITLE
"OutOfBounds" error when generating a GF store

### ISSUE THREAD

**Issue by jbehura** [hvasbath/beat#100]
Hi 

[config.txt](https://github.com/hvasbath/beat/files/8492475/config.txt)

When using the above config file to generate a GF store, I get an error "pyrocko.gf.meta.OutOfBounds: out of bounds"

Any ideas what I am missing?

Thanks,
Jyoti

**Comment by hvasbath** [comment]
Please post the full error traceback and what command you executed. This belongs to the pyrocko repository and is unrelated to BEAT. Please re-open there. Closing here.
