### ISSUE TITLE
pyrocko.gf.store_ext.StoreExtError: NTARGETS_OUT_OF_BOUNDS

### ISSUE THREAD

**Issue by wangjieh** [hvasbath/beat#122]
When I use "beat sample project_name --hypers", an error of "pyrocko.gf.store_ext.StoreExtError: NTARGETS_OUT_OF_BOUNDS" occurs, how can I solve it?

**Comment by hvasbath** [comment]
Without the full error traceback I can only speculate. So please see FAQ point 6 here please: https://pyrocko.org/beat/docs/current/faq.html

**Comment by wangjieh** [comment]
Ok, Taank you!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hvasbath/beat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月17日(星期四) 下午5:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hvasbath/beat] pyrocko.gf.store_ext.StoreExtError: NTARGETS_OUT_OF_BOUNDS (Issue #122)





 
Without the full error traceback I can only speculate. So please see FAQ point 6 here please: https://pyrocko.org/beat/docs/current/faq.html
