### ISSUE TITLE
sac file can not transform right format

### ISSUE THREAD

**Issue by wushaoyu0** [hvasbath/beat#123]
Hello professor, I encountered an error when converting the SAC format to mseed format using the convert_sac_mseed.py scrip.
I don't know much about seismic wave data. Can you provide me with a detailed processing process?  I want use my sac file import the sesmic data in the right format. Thank you very much.
![image](https://github.com/hvasbath/beat/assets/52923901/3895c751-9669-4427-a57b-9019fed0cd56)

**Comment by hvasbath** [comment]
This is the wrong location. Please post this to the pyrocko support channel or the pyrocko git here: https://git.pyrocko.org/pyrocko/pyrocko/issues
