### ISSUE TITLE
Questions about BEAT?

### ISSUE THREAD

**Issue by sangchengfang** [hvasbath/beat#130]
Hello, I have two questions about BEAT.

1. I do not understand the meaning of east_shift and north_shift in example 3.
The document says that the location parameters of the event are used as the reference point, but what about the reference point of the fault?

2. I want to estimate the locations and geometry of two faults for one earthquake because, based on the aftershock distribution, it could be possible that the event ruptured two faults. I saw that we could use multiple sources in BEAT (https://pubs.geoscienceworld.org/ssa/srl/article-abstract/91/2A/1003/580479/The-Bayesian-Earthquake-Analysis-Tool?redirectedFrom=fulltext), but I am not quite clear on how to set up a proper config file to do this.
Could you give me some suggestions or an example config file for that?

Thank you.

**Comment by hvasbath** [comment]
Hello again!
1) The reference point on the fault is the centre of the top fault edge. East and north shifts are the distances in km to the reference location as defined in the event location.
2) Just do:
beat init "$two_faultsetup_name" --n_sources=2 --source_types=RectangularSource --datatypes=...

**Comment by sangchengfang** [comment]
Thanks for your suggestions!
