### ISSUE TITLE
How to export standard deviation of "ffi" fault slip?

### ISSUE THREAD

**Issue by sangchengfang** [hvasbath/beat#133]
Hello,
I am now trying to plot the inverted fault slip. The two components of "uparr" and "uperp" have been exported by running:
```
beat export proj_dir --mode=ffi --stage_number=-1
```
I also want to plot the slip vector with uncertainty ellipses on the subfaults (just like what the best software does), but I cannot find them in the exported files. I noted that the standard deviations of parameters of the mean solution had been presented in "summary.txt", but I did not find an option that specifies the solution type when we summarized the project.

So the problem is how can we access the standard deviation of the MAP solution or is there any option to export these values?

Any suggestions to work around this problem.
Thanks.

**Comment by hvasbath** [comment]
You need to load the result trace, extract the ensemble of the parameters and calculate the stds from the ensemble.
This is how you could load the result trace, obviously you would need to edit the paths and  variable names you want to extract.

```python
from beat import backend
from os import path as op

varnames=['strike', 'dip', 'rake']   # put any variable name there (naming needs to be identical as in for example stage_-1.pdf plot)
projectdir = '/path/to/project'      # path to your BEAT project

# this assumes you have run beat export first
mtrace = backend.load_multitrace(
    dirname=op.join(projectdir, 'geometry', 'results'),
    chains=[-1], varnames=varnames, backend='bin')

sampling_variables = {}
for varname in varnames:
    sampling_variables[varname] = mtrace.get_values(
        varname, combine=True, squeeze=True)

# this will give you a dictionary with numpy arrays with the variable name as keys
# you can plot these than using familiar plotting libraries like matplotlib or seaborn
```

**Comment by hvasbath** [comment]
I added this very script to the FAQ of the webpage for v2.0.3

**Comment by sangchengfang** [comment]
Sorry, I forgot to report follow-up information here, I have finished it, and your suggestion is helpful, thanks again.

**Comment by sangchengfang** [comment]
I found that the std in the "summary.txt" is enough because although the solutions are different (mean or MAP), the distributions are the same.
