### ISSUE TITLE
How to adjust the Prior parameter in beat

### ISSUE THREAD

**Issue by CUMT530849827** [hvasbath/beat#140]
Hello, Professor I used beat to model the insar data, I used the parameters given by gcmt as the prior value to set the Prior, after many times of modifying the parameters to run, I think I got a good result, but the slip parameter keeps showing very badly, the upper boundary feels incorrect, how should I adjust these parameters, can you tell me some experience?

![image](https://github.com/user-attachments/assets/f0e92208-16f0-4f36-95ff-40554d8dbc0a)
![image](https://github.com/user-attachments/assets/14c84803-ce38-4742-aec1-9da6a613bbdd)
![image](https://github.com/user-attachments/assets/6554e411-449d-44e4-970f-13536db34bdf)

--- !beat.BEATconfig
name: wsEQ
date: '2024-01-23'
event: !pf.Event
  lat: 41.12
  lon: 78.55
  time: '2024-01-23 20:38:14.789999962'
  depth: 12000.0
  name: '202401232038A'
  magnitude: 5.333618813915386
  region: 'KYRGYZSTAN-XINJIANG BORD'
  catalog: 'gCMT'
  moment_tensor: !pf.MomentTensor
    mnn: -1.07e+17
    mee: 6100000000000000.0
    mdd: 1.01e+17
    mne: 2.8000000000000004e+16
    mnd: -1.23e+16
    med: 2.8899999999999996e+16
    strike1: 242.7282658697674
    dip1: 51.69651014850088
    rake1: 71.37524839642086
    strike2: 91.26249894139745
    dip2: 41.95738720304014
    rake2: 112.01546783226685
    moment: 1.1231253269337309e+17
    magnitude: 5.333618813915386
  duration: 2.2
project_dir: /root/Desktop/wsbt/wsEQ
problem_config: !beat.ProblemConfig
  mode: geometry
  source_types:
  - RectangularSource
  stf_type: HalfSinusoid
  decimation_factors:
    geodetic: 4
  n_sources:
  - 1
  datatypes:
  - geodetic
  hyperparameters:
    h_SAR: !beat.heart.Parameter
      name: h_SAR
      form: Uniform
      lower:
      - 1.0
      upper:
      - 6.0
      testvalue:
      - 3.5
  priors:
    depth: !beat.heart.Parameter
      name: depth
      form: Uniform
      lower:
      - 0.0
      upper:
      - 15.0
      testvalue:
      - 8.0
    dip: !beat.heart.Parameter
      name: dip
      form: Uniform
      lower:
      - 0.0
      upper:
      - 90.0
      testvalue:
      - 55.0
    east_shift: !beat.heart.Parameter
      name: east_shift
      form: Uniform
      lower:
      - -10.0
      upper:
      - 10.0
      testvalue:
      - 0.0
    length: !beat.heart.Parameter
      name: length
      form: Uniform
      lower:
      - 5.0
      upper:
      - 50.0
      testvalue:
      - 34.0
    north_shift: !beat.heart.Parameter
      name: north_shift
      form: Uniform
      lower:
      - -10.0
      upper:
      - 10.0
      testvalue:
      - 5.0
    nucleation_x: !beat.heart.Parameter
      name: nucleation_x
      form: Uniform
      lower:
      - -1.0
      upper:
      - 1.0
      testvalue:
      - 0.0
    nucleation_y: !beat.heart.Parameter
      name: nucleation_y
      form: Uniform
      lower:
      - -1.0
      upper:
      - 1.0
      testvalue:
      - 0.0
    rake: !beat.heart.Parameter
      name: rake
      form: Uniform
      lower:
      - -180.0
      upper:
      - 180.0
      testvalue:
      - 71.0
    slip: !beat.heart.Parameter
      name: slip
      form: Uniform
      lower:
      - 0.0
      upper:
      - 10.0
      testvalue:
      - 5.0
    strike: !beat.heart.Parameter
      name: strike
      form: Uniform
      lower:
      - 0.0
      upper:
      - 180.0
      testvalue:
      - 60.0
    time: !beat.heart.Parameter
      name: time
      form: Uniform
      lower:
      - -80.0
      upper:
      - 40.0
      testvalue:
      - 2.0
    width: !beat.heart.Parameter
      name: width
      form: Uniform
      lower:
      - 0.0
      upper:
      - 16.0
      testvalue:
      - 8.0
  hierarchicals:
    wsas1_azimuth_ramp: !beat.heart.Parameter
      name: wsas1_azimuth_ramp
      form: Uniform
      lower:
      - -0.005
      upper:
      - 0.005
      testvalue:
      - 0.0
    wsas1_offset: !beat.heart.Parameter
      name: wsas1_offset
      form: Uniform
      lower:
      - -0.05
      upper:
      - 0.05
      testvalue:
      - 0.005
    wsas1_range_ramp: !beat.heart.Parameter
      name: wsas1_range_ramp
      form: Uniform
      lower:
      - -0.005
      upper:
      - 0.005
      testvalue:
      - 0.0
geodetic_config: !beat.GeodeticConfig
  types:
    SAR: !beat.SARDatasetConfig
      datadir: /root/Desktop/wsbt
      names:
      - wsas1
  noise_estimator: !beat.GeodeticNoiseAnalyserConfig
    structure: import
    max_dist_perc: 0.2
  interpolation: multilinear
  corrections_config: !beat.GeodeticCorrectionsConfig
    euler_poles:
    - !beat.EulerPoleConfig
      enabled: false
    ramp: !beat.RampConfig
      dataset_names:
      - wsas1
      enabled: true
    strain_rates:
    - !beat.StrainRateConfig
      enabled: false
  dataset_specific_residual_noise_estimation: true

**Comment by hvasbath** [comment]
You only have a single dataset to constrain your observation, which makes the problem fairly illposed. 
Most noticable: The gCMT solution shows a Mw of 5.3, that would be an earthquake of a rupture plane 5-8km times 5-8 km with slip of 10cm on that order. You now have a 5km wide fault with 35km length and 10m slip, that is still trying to increase slip to fit fullfill the moment requirement. Which is rather a magnitude 6.5+ earthquake. Without seeing your data I think your data units are wrong. Your LOS displacements need to be in meter. I think you have now cm.

**Comment by hvasbath** [comment]
Not sure which Gaussian distribution you are referring to, but you should not expect any sampled distribution to be strictly Gaussian- why should they be Gaussian?

You are hitting the bounds especially in h_SAR and h_laplacian, So please reduce the lower bounds of both, I would suggest h_SAR to 0 and enable dataset_specific_residual_noise estimation flag- your datasets show different noise characteristics as you can see in your histograms right panels. h_laplacian maybe to 1.

**Comment by CUMT530849827** [comment]
@hvasbath 
Dear Professor, I changed the parameters of h_SAR and h_laplacian according to what you said. I used beat update, but when I conducted beat sample, I found that it automatically modified the range of upper and lower bounds of h_SAR and h_laplacian. Back to the original parameter, what is the reason for this? What should I do
![image](https://github.com/user-attachments/assets/957365e4-59ac-4627-9dc0-17074ca98391)

![image](https://github.com/user-attachments/assets/996ded35-b848-45b8-bc2d-2438b97b63f7)

**Comment by CUMT530849827** [comment]
@hvasbath 
I found that he changed the upper and lower bounds in the beat sample wsEQ --hypers --mode=ffi step. What should I do?
[
<img width="572" alt="Snipaste_2024-11-12_23-08-46" src="https://github.com/user-attachments/assets/59b8926b-c298-4589-84cb-228fcb7d2dad">
](url)

**Comment by CUMT530849827** [comment]
@WYM147 
Hello You can delete a few lines related to gnss

**Comment by WYM147** [comment]
> @WYM147 Hello You can delete a few lines related to gnss

Thanks a lot.

**Comment by hvasbath** [comment]
> @hvasbath I found that he changed the upper and lower bounds in the beat sample wsEQ --hypers --mode=ffi step. What should I do? [ <img alt="Snipaste_2024-11-12_23-08-46" width="572" src="https://private-user-images.githubusercontent.com/49933485/385340146-59b8926b-c298-4589-84cb-228fcb7d2dad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MjUyOTIsIm5iZiI6MTczMTQyNDk5MiwicGF0aCI6Ii80OTkzMzQ4NS8zODUzNDAxNDYtNTliODkyNmItYzI5OC00NTg5LTg0Y2ItMjI4ZmNiN2QyZGFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE1MjMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwOGQzYTRiZjVkYTFkYTNhNGY1ZGJlNjU4NjZmMmViNTI5MTg3M2RjOWQwNGUyMGRlOWNmMWU0ZjQyOGFmMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NRo0XdZT35B0TxiUctwhzsha0-0chp3itdUhD01IAtc"> ](url)

Just dont run beat sample --hypers , either use that or update manually. Now you updated manually and running that of course overwrites it again.

**Comment by hvasbath** [comment]
> @hvasbath Hello Professor, I would like to ask if the direction of the arrow in the inversion of the sliding distribution I made with beat is the opposite of the direction of the arrow in other people's papers? I have been troubled by this problem, can you explain it to me?
> 
> This is the graph I came up with using beat ![image](https://private-user-images.githubusercontent.com/49933485/386692868-0db63035-fdc1-4beb-9835-73ef5c6d3db3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2OTE4NTAsIm5iZiI6MTczMTY5MTU1MCwicGF0aCI6Ii80OTkzMzQ4NS8zODY2OTI4NjgtMGRiNjMwMzUtZmRjMS00YmViLTk4MzUtNzNlZjVjNmQzZGIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDE3MjU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjNjg5ZGVmNjE0MjY0Y2RkY2JjOGQ5NzM2NTMyZDM2ZmNlOGNjYjM3ZGIzNDhhMjM2ZDg1OGU2ZmFhNzU1ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TWk7QXCesOCgIp1mO3ZJwA5l7TNfZ-0uDhktxs9gjs8) This is a sliding distribution from other literature ![image](https://private-user-images.githubusercontent.com/49933485/386692717-ab672c96-7d45-47f2-adc4-e472b5cf3864.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2OTE4NTAsIm5iZiI6MTczMTY5MTU1MCwicGF0aCI6Ii80OTkzMzQ4NS8zODY2OTI3MTctYWI2NzJjOTYtN2Q0NS00N2YyLWFkYzQtZTQ3MmI1Y2YzODY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDE3MjU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkNTJlNTc4YzlhOWExZWI5NjY2MTU0Yjk2MGQzYjVlNDViNzQyYjRjZTVmOTBkYjEyYzViYjNiMjE3YWM1N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RuZ6dbY4uARLtWpl2m465Bwd93f-bPXlMvtu4MgHbXI) ![image](https://private-user-images.githubusercontent.com/49933485/386692407-002774b8-24c4-4cfe-a32d-548a691e043d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2OTE4NTAsIm5iZiI6MTczMTY5MTU1MCwicGF0aCI6Ii80OTkzMzQ4NS8zODY2OTI0MDctMDAyNzc0YjgtMjRjNC00Y2ZlLWEzMmQtNTQ4YTY5MWUwNDNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDE3MjU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmZTM4ODkzMDhiNWMzM2IyNjEzYmZhZjdmZjAyMmQ3OTViMTFlZDViNTUxMTYyYmJiNjZlNTBlNjU4NzRhZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.p-G9vrZXBOUqDd5kEgV43BeXOBxlLOfjYH99qfANImc)

Without further information I cannot say anything much. There are obvious other significant large differences for example the vast difference in slip amplitude 4m vs 1m in your inversion. Looking at the rake variability in your model there is basically zero variabilty did you allow for uperp to be sampled? Also The initial reference rake is of importance and of course also the datasets that were used. So without further context I cannot make any statement about the correctness of either results...

**Comment by hvasbath** [comment]
Also is that supposed to be ascending orbit? If so then your los vectors are wrong
![image](https://github.com/user-attachments/assets/50b4e23b-353a-4079-a28b-b807c4255474)

**Comment by CUMT530849827** [comment]
Yes, here are my orbital ascent data

**Comment by hvasbath** [comment]
Yes, then your look vectors are wrong and all your results are meaningless. You need to correct those. See the kite documentation for conventions.

**Comment by CUMT530849827** [comment]
I tried to process the orbital ascent data of another earthquake by kite, but the direction was still the same as yesterday's, or it was wrong. I don't know what went wrong
![image](https://github.com/user-attachments/assets/d40e4250-7951-4768-b8fa-f47a03d1a4e0)

**Comment by hvasbath** [comment]
We are diverging from the topic here.
