### ISSUE TITLE
inputf - WARNING File begin not conform with kite format! Help 

### ISSUE THREAD

**Issue by jieminWang** [hvasbath/beat#142]
Hello, there is a error when i import kite format data. I want to get geodetic_data.pkl from sar data.
I get 20141005_20141122.geo.unw.tif and 20141122_20141228.geo.unw.tif from http://gws-access.ceda.ac.uk/
I convert 20141005_20141122.geo.unw.tif to Laquila_dscxn, 20141122_20141228.geo.unw.tif to Laquila_ascxn use spool. Laquila_dscxn include Laquila_dscxn.npz and Laquila_dscxn.yaml. Laquila_ascxn include Laquila_ascxn.npz and Laquila_ascxn.yaml.
Then i use
beat import $project_dir --datatypes=geodetic --geodetic_format=kite
Shows
inputf - INFO Loading scene: Laquila_dscxn
inputf - WARNING File begin not conform with kite format!
inputf - INFO Loading scene: Laquila_ascxn
inputf - WARNING File end not conform with kite format!
I know the event is not match the name in match the config_geometry.yaml, with a test.

I also download the Laquila_dscxn from https://github.com/braunfuss/laquila_kite_container
The error is the same: inputf - WARNING File begin not conform with kite format!
Thanks.

**Comment by hvasbath** [comment]
Likely your config_geometry.yaml is not formatted correctly. How does the geodetic_config look like?

**Comment by jieminWang** [comment]
Hello
--- !beat.BEATconfig
name: /home/wjm/vasyurhm/BEATS/test
date: '2009-04-06'
event: !pf.Event
  lat: 42.29
  lon: 13.35
  time: '2009-04-06 01:32:49.190000057'
  depth: 12000.0
  name: '200904060132A'
  magnitude: 6.343080192483292
  region: 'CENTRAL ITALY'
  catalog: 'gCMT'
  moment_tensor: !pf.MomentTensor
    mnn: 1.43e+18
    mee: 1.87e+18
    mdd: -3.3e+18
    mne: 1.77e+18
    mnd: -1.43e+18
    med: 2.6900000000000003e+17
    strike1: 120.23408298515041
    dip1: 54.240869089580485
    rake1: -112.81739742081386
    strike2: 335.98575923255856
    dip2: 41.58440373860804
    rake2: -61.69749587601104
    moment: 3.6696131948749036e+18
    magnitude: 6.343080192483292
  duration: 7.0
project_dir: /home/wjm/vasyurhm/BEATS/test
problem_config: !beat.ProblemConfig
  mode: geometry
  source_types:
  - RectangularSource
  stf_type: HalfSinusoid
  decimation_factors:
    geodetic: 4
  n_sources:
  - 1
  datatypes:
  - geodetic
  hyperparameters:
    h_SAR: !beat.heart.Parameter
      name: h_SAR
      form: Uniform
      lower:
      - -2.0
      upper:
      - 6.0
      testvalue:
      - 2.0
  priors:
    depth: !beat.heart.Parameter
      name: depth
      form: Uniform
      lower:
      - 0.0
      upper:
      - 5.0
      testvalue:
      - 2.95
    dip: !beat.heart.Parameter
      name: dip
      form: Uniform
      lower:
      - 35.0
      upper:
      - 65.0
      testvalue:
      - 59.46
    east_shift: !beat.heart.Parameter
      name: east_shift
      form: Uniform
      lower:
      - -5.0
      upper:
      - 20.0
      testvalue:
      - 10.64
    length: !beat.heart.Parameter
      name: length
      form: Uniform
      lower:
      - 5.0
      upper:
      - 25.0
      testvalue:
      - 12.4
    north_shift: !beat.heart.Parameter
      name: north_shift
      form: Uniform
      lower:
      - -15.0
      upper:
      - 10.0
      testvalue:
      - 5.624
    nucleation_x: !beat.heart.Parameter
      name: nucleation_x
      form: Uniform
      lower:
      - -1.0
      upper:
      - 1.0
      testvalue:
      - -0.94
    nucleation_y: !beat.heart.Parameter
      name: nucleation_y
      form: Uniform
      lower:
      - -1.0
      upper:
      - 1.0
      testvalue:
      - -0.09508065
    rake: !beat.heart.Parameter
      name: rake
      form: Uniform
      lower:
      - -180.0
      upper:
      - 0.0
      testvalue:
      - -125.0
    slip: !beat.heart.Parameter
      name: slip
      form: Uniform
      lower:
      - 0.1
      upper:
      - 1.0
      testvalue:
      - 0.634
    strike: !beat.heart.Parameter
      name: strike
      form: Uniform
      lower:
      - 60.0
      upper:
      - 180.0
      testvalue:
      - 143.0
    time: !beat.heart.Parameter
      name: time
      form: Uniform
      lower:
      - -20.0
      upper:
      - 10.0
      testvalue:
      - -10.0
    width: !beat.heart.Parameter
      name: width
      form: Uniform
      lower:
      - 5.0
      upper:
      - 20.0
      testvalue:
      - 10.0
geodetic_config: !beat.GeodeticConfig
  types:
    SAR: !beat.SARDatasetConfig
      datadir: /home/vasyurhm/BEATS/test
      names:
      - Laquila_dscxn
      - Laquila_ascxn
  noise_estimator: !beat.GeodeticNoiseAnalyserConfig
    structure: import
    max_dist_perc: 0.2
  interpolation: multilinear
  corrections_config: !beat.GeodeticCorrectionsConfig
    euler_poles:
    - !beat.EulerPoleConfig
      enabled: false
    ramp: !beat.RampConfig
      dataset_names:
      - Laquila_dscxn
      - Laquila_ascxn
      enabled: true
    strain_rates:
    - !beat.StrainRateConfig
      enabled: false
  dataset_specific_residual_noise_estimation: true
  gf_config: !beat.GeodeticGFConfig
    reference_model_idx: 0
    n_variations:
    - 0
    - 1
    store_superdir: /home/wjm/vasyurhm/GF/
    earth_model_name: ak135-f-continental.m
    nworkers: 4
    use_crust2: false
    replace_water: false
    source_depth_min: 0.0
    source_depth_max: 35.0
    source_depth_spacing: 1.0
    source_distance_radius: 100.0
    source_distance_spacing: 1.0
    error_depth: 0.1
    error_velocities: 0.1
    depth_limit_variation: 600.0
    version: ''
    code: psgrn
    sample_rate: 1.1574074074074073e-05
    sampling_interval: 1.0
    medium_depth_spacing: 1.0
    medium_distance_spacing: 1.0
sampler_config: !beat.SamplerConfig
  name: SMC
  backend: bin
  progressbar: true
  buffer_size: 5000
  buffer_thinning: 10
  parameters: !beat.SMCConfig
    tune_interval: 10
    check_bnd: true
    rm_flag: false
    n_jobs: 4
    n_steps: 100
    n_chains: 1000
    coef_variation: 1.0
    stage: 0
    proposal_dist: MultivariateCauchy
    update_covariances: false
hyper_sampler_config: !beat.SamplerConfig
  name: Metropolis
  backend: bin
  progressbar: true
  buffer_size: 5000
  buffer_thinning: 1000
  parameters: !beat.MetropolisConfig
    tune_interval: 50
    proposal_dist: Normal
    check_bnd: true
    rm_flag: false
    n_jobs: 4
    n_steps: 25000
    n_chains: 12
    thin: 5
    burn: 0.5

**Comment by jieminWang** [comment]
Hello, I get config_geometry.yaml from example, I change sar data, aquila_dscxn.npz and aquila_dscxn.yaml and datadir.
aquila_dscxn.yaml looks like 
%YAML 1.1
# kite.Scene YAML Config
--- !kite.scene.SceneConfig
meta: !kite.scene.Meta
  scene_title: Unnamed Scene
  scene_id: None
  satellite_name: Undefined Mission
  orbital_node: Undefined
  time_master: '2016-12-07 13:09:21.93057394'
  time_slave: '2016-12-20 13:08:45.482000113'
  filename: /home/wjm/vasyurhm/BEATS/test/20141005_20141122.geo.unw.tif
frame: !kite.scene.FrameConfig
  llLat: 46.07033541759499
  llLon: 8.855055600395001
  dN: 0.0009999992100000008
  dE: 0.0009999992100000006
  spacing: degree
quadtree: !kite.quadtree.QuadtreeConfig
  correction: median
  epsilon: 0.07827791571617126
  nan_allowed: 0.9
  tile_size_min: 0.20049984160500015
  tile_size_max: 0.8019993664200006
covariance: !kite.covariance.CovarianceConfig
  noise_coord:
  - 0.5119995955200003
  - 0.5119995955200004
  - 0.5119995955200003
  - 0.5119995955200004
  model_coefficients:
  - 0.0002198355170390725
  - 3265.5736945639214
  model_function: exponential
  sampling_method: spatial
  spatial_bins: 75
  spatial_pairs: 200000
  variance: 0.0002123683090895383
  adaptive_subsampling: true
aps: !kite.aps.APSConfig
  applied: false
gacos: !kite.gacos.GACOSConfig
  applied: false
polygon_mask: !kite.scene_mask.PolygonMaskConfig
  applied: true
deramp: !kite.deramp.DerampConfig
  applied: false
auto make by spool.

**Comment by hvasbath** [comment]
I cannot tell if your indentation is correct if you just dump it like that. Might be a problem with indentation under `SARDatasetConfig`

**Comment by jieminWang** [comment]
![1733140155455](https://github.com/user-attachments/assets/9a59fa13-d261-4a72-bdde-f3313e5688ba)

**Comment by jieminWang** [comment]
The config_geometry.yaml i got it from example 3, the indentation is correct.

**Comment by jieminWang** [comment]
I have found the error where I make. Thanks! 
I make an error indentation in other location. Thank you very much!
