### ISSUE TITLE
How to get FULL original InSAR data in Scenario I?

### ISSUE THREAD

**Issue by vic-chou** [hvasbath/beat#23]
Hi,
When I run "beat plot Laquila scene_fits", I can not get the figures with content. The result figure is blank. I noticed that the Scenario I said to generate the results the FULL original data needs to be downloaded and put into the specified data path. But I don't know how to get the FULL original InSAR data? Can you help me? Thank you!

**Comment by braunfuss** [comment]
Hello, 
you do not have to get the full original InSAR data to plot the modelling results. The "full" in this case just refers to the data after processing with the kite software package - but before we reduce the data to pkl format. 
I uploaded the displacement data for ascending and descending scenes for you (and other users) as kite container here: https://github.com/braunfuss/laquila_kite_container.git
The npz and yml files in that repo need to be in the same data directory as the pkl example data specified in your geodetic config section of the config_geometry.yml, e.g.

 geodetic_config: !beat.GeodeticConfig
datadir:/home/vasyurhm/BEATS/RectangularStatic/insar

Please note that the kite software also needs to be installed: https://github.com/pyrocko/kite
You can also use it to have a closer look at the original displacement data and explore the kite software
functions.

Please tell us if this worked for you. 
Regards
Andreas

**Comment by hvasbath** [comment]
Thanks @braunfuss . A small correction: the npz and yml files do not need to be at the same path as the pkl file. As correctly stated they need to be in the directory path that is specified under the geodetic_config.

**Comment by vic-chou** [comment]
Thanks for your detailed answer! I am running successfully under your suggestion.

**Comment by braunfuss** [comment]
No problem,we are happy to help. Please open a new issue if any other problems arise. Have fun with Beat!
