### ISSUE TITLE
Error: runing "beat build_gfs Laquila_kinematic --datatypes=geodetic --execute --mode=ffo"

### ISSUE THREAD

**Issue by vic-chou** [hvasbath/beat#25]
Hi, when I running "beat build_gfs Laquila_kinematic --datatypes=geodetic --execute --mode=ffo" in Scenario III, I meet an error:
config       - INFO     All parameter-priors ok!
config       - INFO     All hyper-parameters ok!
config       - INFO     All hierarchical-parameters ok!
beat         - INFO     Discretized fault geometry exists! Use --force to overwrite!
beat         - INFO     Loading existing discretized fault
beat         - INFO     Calculating linear Green's Functions
beat         - INFO     for seismic data ...
beat         - INFO     crust_ind 0
heart        - INFO     Consistent number of datasets and targets in any_P_0 wavemap!
heart        - INFO     Number of seismic datasets for wavemap: any_P_0: 35 
ffo          - INFO     Calculating GFs for starttimes: "-10.0", "-9.0", "-8.0", "-7.0", "-6.0", "-5.0", "-4.0", "-3.0", "-2.0", "-1.0", "0.0", "1.0", "2.0", "3.0", "4.0", "5.0", "6.0", "7.0", "8.0", "9.0", "10.0", "11.0", "12.0", "13.0", "14.0", "15.0", "16.0", "17.0", "18.0", "19.0", "20.0", "21.0", "22.0", "23.0", "24.0", "25.0", "26.0", "27.0", "28.0", "29.0", "30.0", "31.0", "32.0" 
 durations: "0.0", "1.0", "2.0", "3.0", "4.0"
ffo          - INFO     Using 1 workers ...
ffo          - INFO     For slip component: uparr
ffo          - INFO     Allocating GF Library
ffo          - INFO     Setting up Green's Function Library: 
Seismic GF Library
------------------
--- !beat.SeismicGFLibraryConfig
component: uparr
event: !pf.Event
  lat: 42.29
  lon: 13.35
  time: 2009-04-06 01:32:49.190000
  name: 200904060132A
  depth: 12000.0
  magnitude: 6.343080192483292
  region: CENTRAL ITALY
  catalog: gCMT
  moment_tensor: !pf.MomentTensor
    mnn: 1.43e+18
    mee: 1.87e+18
    mdd: -3.3e+18
    mne: 1.77e+18
    mnd: -1.43e+18
    med: 2.6900000000000003e+17
    strike1: 120.23408298515041
    dip1: 54.240869089580485
    rake1: -112.81739742081386
    strike2: 335.98575923255856
    dip2: 41.58440373860804
    rake2: -61.69749587601104
    moment: 3.6696131948749036e+18
    magnitude: 6.343080192483292
  duration: 7.0
datatype: seismic
crust_ind: 0
reference_sources:
- !beat.sources.RectangularSource
  lat: 42.29
  lon: 13.35
  north_shift: 6210.765329902994
  east_shift: 12215.633404840579
  elevation: 0.0
  depth: 371.66597868550434
  time: 2009-04-06 01:32:49.190000
  stf: !pf.HalfSinusoidSTF
    duration: 0.0
    anchor: -1.0
  stf_mode: post
  strike: 145.40298276603247
  dip: 54.22973164156763
  rake: -112.79284665995873
  length: 20000.0
  width: 15000.0
  velocity: 3500.0
  slip: 1.0
wave_config: !beat.WaveformFitConfig
  include: true
  preprocess_data: true
  name: any_P
  channels: [Z]
  filterer: !beat.heart.Filter
    lower_corner: 0.001
    upper_corner: 0.1
    order: 4
  distances: [30.0, 90.0]
  interpolation: multilinear
  arrival_taper: !beat.heart.ArrivalTaper
    a: -15.0
    b: -10.0
    c: 50.0
    d: 55.0
starttime_sampling: 1.0
duration_sampling: 1.0
starttime_min: -10.0
duration_min: 0.0
dimensions: [35, 12, 5, 43, 120]

ntargets: 35
npatches: 12
ndurations: 5
nstarttimes: 43
nsamples: 120
size: 10836000
filesize [MB]: 82.672119
filename: seismic_uparr_any_P_0 
 
ffo          - INFO     Patch Number 0
Traceback (most recent call last):
  File "/beat/python35/bin/beat", line 11, in <module>
    load_entry_point('beat==1.0rc1', 'console_scripts', 'beat')()
  File "/.local/lib/python3.5/site-packages/beat-1.0rc1-py3.5-linux-x86_64.egg/beat/apps/beat.py", line 1588, in main
    globals()['command_' + command](args)
  File "/.local/lib/python3.5/site-packages/beat-1.0rc1-py3.5-linux-x86_64.egg/beat/apps/beat.py", line 1144, in command_build_gfs
    force=options.force)
  File "/.local/lib/python3.5/site-packages/beat-1.0rc1-py3.5-linux-x86_64.egg/beat/ffo/base.py", line 1088, in seis_construct_gf_linear
    for res in p:
  File "/.local/lib/python3.5/site-packages/beat-1.0rc1-py3.5-linux-x86_64.egg/beat/parallel.py", line 224, in paripool
    yield [function(*work)]
  File "/.local/lib/python3.5/site-packages/beat-1.0rc1-py3.5-linux-x86_64.egg/beat/ffo/base.py", line 927, in _process_patch_seismic
    outmode='data')
  File "/.local/lib/python3.5/site-packages/beat-1.0rc1-py3.5-linux-x86_64.egg/beat/heart.py", line 2574, in seis_synthetics
    targets=targets, nprocs=nprocs)
  File "/beat/python35/lib/python3.5/site-packages/pyrocko/gf/seismosizer.py", line 3114, in process
    self.get_store(store_id)
  File "/beat/python35/lib/python3.5/site-packages/pyrocko/gf/seismosizer.py", line 2898, in get_store
    store_dir = self.get_store_dir(store_id)
  File "/beat/python35/lib/python3.5/site-packages/pyrocko/gf/seismosizer.py", line 2856, in get_store_dir
    raise NoSuchStore(store_id, self.iter_store_dirs())
pyrocko.gf.seismosizer.NoSuchStore: no GF store with id "TSUM_ak135_2.000Hz_0" found. Searched folders:

I noticed that in "Elementray GFs" of Scenario III, the green function is calculated with "beat build_gfs Laquila --datatypes='seismic' --execute". Should it use "Laquila_kinematic" in this command? Why is the "Laquila" is used here? And I calculated the GFs with 0.5HZ and the error said there is no 2HZ GFs. Can you give me some suggestions?

**Comment by hvasbath** [comment]
Please read again:
https://hvasbath.github.io/beat/examples/FFO_kinematic.html#calculate-green-s-functions
If in there something is unclear please let me know and I will have to work on the text.

**Comment by vic-chou** [comment]
Hi, this "use wavelengths of up to 0.5Hz ergo a depth" refer to which parameter in config_geometry.yaml?

**Comment by hvasbath** [comment]
This does not refer to any parameter. That what follows "ergo a depth and distance sampling of 1 km and 2Hz sample rate may be precise enough" refers to: seismic_config.gf_config: source_depth_spacing,  source_distance_spacing and sample_rate.

**Comment by braunfuss** [comment]
Just some comments/rephrasing from my side to maybe clarify: The parameter sample_rate in the gf_config section has to match your GF store sampling rate. 
Note that the sampling rate is given in HZ. 

In the example wavelengths of up to 0.5Hz are used, so that a Green's function needs to have at absolute least 1Hz sampling (Nyquist freq.), but higher is better. With your calculated a GF store at 0.5Hz you will not be able to model at the examples frequencies.

**Comment by vic-chou** [comment]
But when I run "beat plot Laquila_kinematic scene_fits --mode=ffo", I meet an error:
beat         - INFO     Loading problem ...
config       - INFO     All parameter-priors ok!
config       - INFO     All hyper-parameters ok!
config       - INFO     All hierarchical-parameters ok!
models       - INFO     ... Initialising Distribution Optimizer ... 

models       - INFO     Analysing problem ...
models       - INFO     ---------------------

geodetic     - INFO     Number of geodetic datasets: 2 
geodetic     - INFO     Number of geodetic data points: 419 
geodetic     - WARNING  Covariance estimation not implemented (yet)! Using imported covariances!
heart        - INFO     Consistent number of datasets and targets in any_P_0 wavemap!
heart        - INFO     Number of seismic datasets for wavemap: any_P_0: 35 
seismic      - INFO     Fault(s) discretized to "5.0" [km] patches.
seismic      - INFO     Preparing data of "any_P" for optimization
models       - INFO     Using "none" regularization ...
backend      - INFO     Loading multitrace from beat/test_beat/Laquila_kinematic/ffo/stage_-1
geodetic     - INFO     Initialized 0 hierarchical parameters (ramps).
plotting     - INFO     FFO scene fit, using reference source ...
plotting     - INFO     Loading full resolution kite scene: beat/test_beat/Laquila_insar_data/laquila_kite_container-master/Laquila_dscxn
plotting     - INFO     Plotting obs
plotting     - INFO     Plotting syn
plotting     - INFO     Plotting res
plotting     - INFO     Plotting reference sources
plotting     - INFO     Loading full resolution kite scene: beat/test_beat/Laquila_insar_data/laquila_kite_container-master/Laquila_ascxn
plotting     - INFO     Plotting obs
plotting     - INFO     Plotting syn
plotting     - INFO     Plotting res
plotting     - INFO     Plotting reference sources
plotting     - INFO     saving figures to beat/test_beat/Laquila_kinematic/ffo/figures/scenes_-1_max_local
[gyxu@insar test_beat]$ beat plot Laquila_kinematic waveform_fits --mode=ffo
beat         - INFO     Loading problem ...
config       - INFO     All parameter-priors ok!
config       - INFO     All hyper-parameters ok!
config       - INFO     All hierarchical-parameters ok!
models       - INFO     ... Initialising Distribution Optimizer ... 

models       - INFO     Analysing problem ...
models       - INFO     ---------------------

geodetic     - INFO     Number of geodetic datasets: 2 
geodetic     - INFO     Number of geodetic data points: 419 
geodetic     - WARNING  Covariance estimation not implemented (yet)! Using imported covariances!
heart        - INFO     Consistent number of datasets and targets in any_P_0 wavemap!
heart        - INFO     Number of seismic datasets for wavemap: any_P_0: 35 
seismic      - INFO     Fault(s) discretized to "5.0" [km] patches.
seismic      - INFO     Preparing data of "any_P" for optimization
models       - INFO     Using "none" regularization ...
backend      - INFO     Loading multitrace from beat/test_beat/Laquila_kinematic/ffo/stage_-1
plotting     - INFO     FFO waveform fit, using reference source ...
plotting     - INFO     Plotting waveforms ...
plotting     - INFO     saving figures to beat/test_beat/Laquila_kinematic/ffo/figures/waveforms_-1_max
[gyxu@insar test_beat]$ beat plot Laquila_kinematic moment_rate --mode=ffo
beat         - INFO     Loading problem ...
config       - INFO     All parameter-priors ok!
config       - INFO     All hyper-parameters ok!
config       - INFO     All hierarchical-parameters ok!
models       - INFO     ... Initialising Distribution Optimizer ... 

models       - INFO     Analysing problem ...
models       - INFO     ---------------------

geodetic     - INFO     Number of geodetic datasets: 2 
geodetic     - INFO     Number of geodetic data points: 419 
geodetic     - WARNING  Covariance estimation not implemented (yet)! Using imported covariances!
heart        - INFO     Consistent number of datasets and targets in any_P_0 wavemap!
heart        - INFO     Number of seismic datasets for wavemap: any_P_0: 35 
seismic      - INFO     Fault(s) discretized to "5.0" [km] patches.
seismic      - INFO     Preparing data of "any_P" for optimization
models       - INFO     Using "none" regularization ...
backend      - INFO     Loading multitrace from beat/test_beat/Laquila_kinematic/ffo/stage_-1
plotting     - INFO     Drawing ensemble of moment rate functions ...
plotting     - INFO     saving figure to beat/test_beat/Laquila_kinematic/ffo/figures/moment_rate_-1_0_max.pdf
[gyxu@insar test_beat]$ beat plot Laquila_kinematic slip_distribution --mode=ffo
beat         - INFO     Loading problem ...
config       - INFO     All parameter-priors ok!
config       - INFO     All hyper-parameters ok!
config       - INFO     All hierarchical-parameters ok!
models       - INFO     ... Initialising Distribution Optimizer ... 

models       - INFO     Analysing problem ...
models       - INFO     ---------------------

geodetic     - INFO     Number of geodetic datasets: 2 
geodetic     - INFO     Number of geodetic data points: 419 
geodetic     - WARNING  Covariance estimation not implemented (yet)! Using imported covariances!
heart        - INFO     Consistent number of datasets and targets in any_P_0 wavemap!
heart        - INFO     Number of seismic datasets for wavemap: any_P_0: 35 
seismic      - INFO     Fault(s) discretized to "5.0" [km] patches.
seismic      - INFO     Preparing data of "any_P" for optimization
models       - INFO     Using "none" regularization ...
backend      - INFO     Loading multitrace from beat/test_beat/Laquila_kinematic/ffo/stage_-1
Traceback (most recent call last):
  File "beat/python35/bin/beat", line 11, in <module>
    load_entry_point('beat==1.0rc1', 'console_scripts', 'beat')()
  File ".local/lib/python3.5/site-packages/beat-1.0rc1-py3.5-linux-x86_64.egg/beat/apps/beat.py", line 1588, in main
    globals()['command_' + command](args)
  File ".local/lib/python3.5/site-packages/beat-1.0rc1-py3.5-linux-x86_64.egg/beat/apps/beat.py", line 1295, in command_plot
    plotting.plots_catalog[plot](problem, po)
  File ".local/lib/python3.5/site-packages/beat-1.0rc1-py3.5-linux-x86_64.egg/beat/plotting.py", line 2655, in draw_slip_dist
    fault, mtrace, transform=transform, reference=reference)
  File ".local/lib/python3.5/site-packages/beat-1.0rc1-py3.5-linux-x86_64.egg/beat/plotting.py", line 2532, in fault_slip_distribution
    alpha=1., linewidth=7, zorder=-1)
  File ".local/lib/python3.5/site-packages/beat-1.0rc1-py3.5-linux-x86_64.egg/beat/plotting.py", line 2368, in fuzzy_rupture_fronts
    linewidth=linewidth)
  File ".local/lib/python3.5/site-packages/beat-1.0rc1-py3.5-linux-x86_64.egg/beat/plotting.py", line 2819, in draw_line_on_array
    check_grid_shape(ngr, naim, axis)
  File ".local/lib/python3.5/site-packages/beat-1.0rc1-py3.5-linux-x86_64.egg/beat/plotting.py", line 2777, in check_grid_shape
    ' Expected %i got %i' % (axis, naim, ngr))
TypeError: Gridsize of given grid is inconistent for axis 0! Expected 250 got 375

Other command can run successfully except the plot of slip distribution. Can you give me some suggestion?

**Comment by hvasbath** [comment]
Can you please open another issue? This is important to keep track! I will close this one as resolved

**Comment by vic-chou** [comment]
OK
