### ISSUE TITLE
BUG in slip-distribution plot

### ISSUE THREAD

**Issue by vic-chou** [hvasbath/beat#26]
But when I run "beat plot Laquila_kinematic scene_fits --mode=ffo" in Scenario III, I meet an error:
beat - INFO Loading problem ...
config - INFO All parameter-priors ok!
config - INFO All hyper-parameters ok!
config - INFO All hierarchical-parameters ok!
models - INFO ... Initialising Distribution Optimizer ...

models - INFO Analysing problem ...
models - INFO ---------------------

geodetic - INFO Number of geodetic datasets: 2
geodetic - INFO Number of geodetic data points: 419
geodetic - WARNING Covariance estimation not implemented (yet)! Using imported covariances!
heart - INFO Consistent number of datasets and targets in any_P_0 wavemap!
heart - INFO Number of seismic datasets for wavemap: any_P_0: 35
seismic - INFO Fault(s) discretized to "5.0" [km] patches.
seismic - INFO Preparing data of "any_P" for optimization
models - INFO Using "none" regularization ...
backend - INFO Loading multitrace from beat/test_beat/Laquila_kinematic/ffo/stage_-1
geodetic - INFO Initialized 0 hierarchical parameters (ramps).
plotting - INFO FFO scene fit, using reference source ...
plotting - INFO Loading full resolution kite scene: beat/test_beat/Laquila_insar_data/laquila_kite_container-master/Laquila_dscxn
plotting - INFO Plotting obs
plotting - INFO Plotting syn
plotting - INFO Plotting res
plotting - INFO Plotting reference sources
plotting - INFO Loading full resolution kite scene: beat/test_beat/Laquila_insar_data/laquila_kite_container-master/Laquila_ascxn
plotting - INFO Plotting obs
plotting - INFO Plotting syn
plotting - INFO Plotting res
plotting - INFO Plotting reference sources
plotting - INFO saving figures to beat/test_beat/Laquila_kinematic/ffo/figures/scenes_-1_max_local
[gyxu@insar test_beat]$ beat plot Laquila_kinematic waveform_fits --mode=ffo
beat - INFO Loading problem ...
config - INFO All parameter-priors ok!
config - INFO All hyper-parameters ok!
config - INFO All hierarchical-parameters ok!
models - INFO ... Initialising Distribution Optimizer ...

models - INFO Analysing problem ...
models - INFO ---------------------

geodetic - INFO Number of geodetic datasets: 2
geodetic - INFO Number of geodetic data points: 419
geodetic - WARNING Covariance estimation not implemented (yet)! Using imported covariances!
heart - INFO Consistent number of datasets and targets in any_P_0 wavemap!
heart - INFO Number of seismic datasets for wavemap: any_P_0: 35
seismic - INFO Fault(s) discretized to "5.0" [km] patches.
seismic - INFO Preparing data of "any_P" for optimization
models - INFO Using "none" regularization ...
backend - INFO Loading multitrace from beat/test_beat/Laquila_kinematic/ffo/stage_-1
plotting - INFO FFO waveform fit, using reference source ...
plotting - INFO Plotting waveforms ...
plotting - INFO saving figures to beat/test_beat/Laquila_kinematic/ffo/figures/waveforms_-1_max
[gyxu@insar test_beat]$ beat plot Laquila_kinematic moment_rate --mode=ffo
beat - INFO Loading problem ...
config - INFO All parameter-priors ok!
config - INFO All hyper-parameters ok!
config - INFO All hierarchical-parameters ok!
models - INFO ... Initialising Distribution Optimizer ...

models - INFO Analysing problem ...
models - INFO ---------------------

geodetic - INFO Number of geodetic datasets: 2
geodetic - INFO Number of geodetic data points: 419
geodetic - WARNING Covariance estimation not implemented (yet)! Using imported covariances!
heart - INFO Consistent number of datasets and targets in any_P_0 wavemap!
heart - INFO Number of seismic datasets for wavemap: any_P_0: 35
seismic - INFO Fault(s) discretized to "5.0" [km] patches.
seismic - INFO Preparing data of "any_P" for optimization
models - INFO Using "none" regularization ...
backend - INFO Loading multitrace from beat/test_beat/Laquila_kinematic/ffo/stage_-1
plotting - INFO Drawing ensemble of moment rate functions ...
plotting - INFO saving figure to beat/test_beat/Laquila_kinematic/ffo/figures/moment_rate_-1_0_max.pdf
[gyxu@insar test_beat]$ beat plot Laquila_kinematic slip_distribution --mode=ffo
beat - INFO Loading problem ...
config - INFO All parameter-priors ok!
config - INFO All hyper-parameters ok!
config - INFO All hierarchical-parameters ok!
models - INFO ... Initialising Distribution Optimizer ...

models - INFO Analysing problem ...
models - INFO ---------------------

geodetic - INFO Number of geodetic datasets: 2
geodetic - INFO Number of geodetic data points: 419
geodetic - WARNING Covariance estimation not implemented (yet)! Using imported covariances!
heart - INFO Consistent number of datasets and targets in any_P_0 wavemap!
heart - INFO Number of seismic datasets for wavemap: any_P_0: 35
seismic - INFO Fault(s) discretized to "5.0" [km] patches.
seismic - INFO Preparing data of "any_P" for optimization
models - INFO Using "none" regularization ...
backend - INFO Loading multitrace from beat/test_beat/Laquila_kinematic/ffo/stage_-1
Traceback (most recent call last):
File "beat/python35/bin/beat", line 11, in 
load_entry_point('beat==1.0rc1', 'console_scripts', 'beat')()
File ".local/lib/python3.5/site-packages/beat-1.0rc1-py3.5-linux-x86_64.egg/beat/apps/beat.py", line 1588, in main
globals()'command_' + command
File ".local/lib/python3.5/site-packages/beat-1.0rc1-py3.5-linux-x86_64.egg/beat/apps/beat.py", line 1295, in command_plot
plotting.plots_catalog[plot](problem, po)
File ".local/lib/python3.5/site-packages/beat-1.0rc1-py3.5-linux-x86_64.egg/beat/plotting.py", line 2655, in draw_slip_dist
fault, mtrace, transform=transform, reference=reference)
File ".local/lib/python3.5/site-packages/beat-1.0rc1-py3.5-linux-x86_64.egg/beat/plotting.py", line 2532, in fault_slip_distribution
alpha=1., linewidth=7, zorder=-1)
File ".local/lib/python3.5/site-packages/beat-1.0rc1-py3.5-linux-x86_64.egg/beat/plotting.py", line 2368, in fuzzy_rupture_fronts
linewidth=linewidth)
File ".local/lib/python3.5/site-packages/beat-1.0rc1-py3.5-linux-x86_64.egg/beat/plotting.py", line 2819, in draw_line_on_array
check_grid_shape(ngr, naim, axis)
File ".local/lib/python3.5/site-packages/beat-1.0rc1-py3.5-linux-x86_64.egg/beat/plotting.py", line 2777, in check_grid_shape
' Expected %i got %i' % (axis, naim, ngr))
TypeError: Gridsize of given grid is inconistent for axis 0! Expected 250 got 375

Other command can run successfully except the plot of slip distribution. Can you give me some suggestion?

**Comment by hvasbath** [comment]
I will have to investigate if there is a bug in the code- this will take time. Thanks for reporting!

**Comment by vic-chou** [comment]
OK, thank you!

**Comment by hvasbath** [comment]
I cannot reproduce your error with the sampling results I have at hand- they all work fine.
Can you please send me your files via mail so that I can try to reproduce your error? I need:
-config_ffo.yaml
-BEAT_log.txt
-chain--1.csv (from the Laquila_kinematic/ffo/stage_-1 directory)
Thanks a lot!

**Comment by vic-chou** [comment]
OK, I have send the files you need via mail.

**Comment by hvasbath** [comment]
Great thanks got it and can reproduce the error! Will keep you posted once I fixed it!

**Comment by vic-chou** [comment]
OK, Thank you.

**Comment by hvasbath** [comment]
please update BEAT. It is fixed and should be working now.

**Comment by vic-chou** [comment]
I update BEAT and now can run it successfully. Thank you!
