### ISSUE TITLE
Warning: The source's sub-sources are further than lambda_min/4 apart

### ISSUE THREAD

**Issue by vic-chou** [hvasbath/beat#28]
Hi, when I run "beat sample Laquila" in Scenario I, there are many WARNING said that "The source's sub-sources are further than lambda_min/4 apart". Does it matter?

**Comment by hvasbath** [comment]
Meaning that your decimation factor (see config_geometry.yaml) is to high or respectively your GF store spacings too low. 
This is not so serious if you are just testing or not doing any kinematic rupture simulation. It introduces numerical errors through coarser descretization by gaining computational speed.

**Comment by vic-chou** [comment]
OK, thank you.
