### ISSUE TITLE
Question about beatdown 

### ISSUE THREAD

**Issue by vic-chou** [hvasbath/beat#33]
Hi, I look at the tutorial about the beatdown, I want to know that how can I download the seismic data of stations with epicentral distance 30-90 degree? Whether I should download the available data in a radius of 1000 km and then select data with epicentral distance 30-90 degree?

**Comment by braunfuss** [comment]
Maybe we should include a degree input for beatdown. In the meantime: if you need help calculating degree to km i recommend using the pyrocko function cakes inbuilt converter factor d2m.

The conversion than could look like this: 

from pyrocko import cake
km = 1000.
dmin = 30.*cake.d2m/km
dmax = 90.*cake.d2m/km

**Comment by vic-chou** [comment]
OK, thank you!

**Comment by hvasbath** [comment]
Thanks @braunfuss for answering. Can you please add that to the tutorial? Editing the function itself just generates a mess dont you think? People should be capable of doing this calculation even in their heads ...

**Comment by braunfuss** [comment]
agreed. added to documentation for beatdown.
