### ISSUE TITLE
Error when running 'beat build_gfs FullMT --datatypes='seismic' --force --execute' 

### ISSUE THREAD

**Issue by vic-chou** [hvasbath/beat#43]
Hi, when I run 'beat build_gfs FullMT --datatypes='seismic' --force --execute' with the dataset that I download using 'beatdown', I meet an error said that:

beat build_gfs FullMT --datatypes='seismic' --force --execute
config       - INFO     All hierarchicals ok!
config       - INFO     All hyperparameters ok!
config       - INFO     All priors ok!
beat         - INFO     Creating Green's Function stores individually for each station!
heart        - INFO     Using crust2 profile
heart        - INFO     Water layer 1329.000000 in CRUST model! Remove and add to lower crust
heart        - INFO     New Lower crust layer thickness 11995.000000
heart        - INFO     Station SOCY
heart        - INFO     ---------------------
heart        - INFO     Creating Store at ./SOCY_ak135_2.000Hz_0
heart        - INFO     Using crust2 profile
heart        - INFO     Water layer 1792.000000 in CRUST model! Remove and add to lower crust
heart        - INFO     New Lower crust layer thickness 6958.000000
heart        - INFO     Filling store ...
pyrocko.gf.store - INFO     making travel time table for phasegroup "any_P"
pyrocko.spit - INFO     at level  0:  100.0% covered,      1 cell
pyrocko.gf.store - INFO     making travel time table for phasegroup "any_S"
pyrocko.spit - INFO     at level  0:    0.0% covered,      1 cell
pyrocko.spit - INFO     at level  1:  100.0% covered,      3 cells
pyrocko.fomosto.qssp - INFO     Starting step 1 / 2, block 1 / 11
pyrocko.fomosto.qssp - INFO     Starting step 1 / 2, block 3 / 11
pyrocko.fomosto.qssp - INFO     Starting step 1 / 2, block 2 / 11
pyrocko.fomosto.qssp - INFO     Starting step 1 / 2, block 4 / 11
pyrocko.fomosto.qssp - WARNING  qssp emitted something via stderr: 

Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL

pyrocko.fomosto.qssp - INFO     Done with step 1 / 2, block 1 / 11, wallclock time: 3229 s
pyrocko.fomosto.qssp - INFO     Starting step 1 / 2, block 5 / 11
pyrocko.fomosto.qssp - WARNING  qssp emitted something via stderr: 

Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL

pyrocko.fomosto.qssp - INFO     Done with step 1 / 2, block 2 / 11, wallclock time: 3274 s
pyrocko.fomosto.qssp - WARNING  qssp emitted something via stderr: 

Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL

pyrocko.fomosto.qssp - INFO     Done with step 1 / 2, block 3 / 11, wallclock time: 3278 s
pyrocko.fomosto.qssp - WARNING  qssp emitted something via stderr: 

Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL

pyrocko.fomosto.qssp - INFO     Done with step 1 / 2, block 4 / 11, wallclock time: 3279 s
Traceback (most recent call last):
  File "/usr/local/bin/beat", line 9, in <module>
    load_entry_point('beat==1.0', 'console_scripts', 'beat')()
  File "/usr/local/lib/python3.6/dist-packages/beat-1.0-py3.6-linux-x86_64.egg/beat/apps/beat.py", line 1641, in main
    globals()['command_' + command](args)
  File "/usr/local/lib/python3.6/dist-packages/beat-1.0-py3.6-linux-x86_64.egg/beat/apps/beat.py", line 1005, in command_build_gfs
    force=options.force)
  File "/usr/local/lib/python3.6/dist-packages/beat-1.0-py3.6-linux-x86_64.egg/beat/heart.py", line 1709, in seis_construct_gf
    store_dir, nworkers=sf.nworkers, force=force)
  File "/usr/local/lib/python3.6/dist-packages/pyrocko/fomosto/qssp.py", line 890, in build
    step=step, iblock=iblock)
  File "/usr/local/lib/python3.6/dist-packages/pyrocko/gf/builder.py", line 166, in build
    Interrupted, store.StoreError)):
  File "/usr/local/lib/python3.6/dist-packages/pyrocko/parimap.py", line 136, in parimap
    raise exc
pyrocko.fomosto.qssp.QSSPError: ===== begin qssp input =====
# autogenerated QSSP input by qssp.py
#
# This is the input file of FORTRAN77 program "qssp2010" for calculating
# synthetic seismograms of a self-gravitating, spherically symmetric,
# isotropic and viscoelastic earth.
#
# by
# Rongjiang  Wang <wang@gfz-potsdam.de>
# Helmholtz-Centre Potsdam
# GFZ German Reseach Centre for Geosciences
# Telegrafenberg, D-14473 Potsdam, Germany
#
# Last modified: Potsdam, July, 2010
#
# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
# If not specified, SI Unit System is used overall!
#
# Coordinate systems:
# spherical (r,t,p) with r = radial,
#                        t = co-latitude,
#                        p = east longitude.
# = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
#
#	UNIFORM RECEIVER DEPTH
#	======================
# 1. uniform receiver depth [km]
#-------------------------------------------------------------------------------------------
    0.000000e+00
#-------------------------------------------------------------------------------------------
#
#	TIME (FREQUENCY) SAMPLING
#	=========================
# 1. time window [sec], sampling interval [sec]
# 2. max. frequency [Hz] of Green's functions
# 3. max. slowness [s/km] of Green's functions
#    Note: if the near-field static displacement is desired, the maximum slowness should not
#          be smaller than the S wave slowness in the receiver layer
# 4. anti-aliasing factor (> 0 & < 1), if it is <= 0 or >= 1/e (~ 0.4), then
#    default value of 1/e is used (e.g., 0.1 = alias phases will be suppressed
#    to 10% of their original amplitude)
#
#    Note: The computation effort increases linearly the time window and
#          quadratically with the cut-off frequency.
#-------------------------------------------------------------------------------------------
    7.385000e+02   5.000000e-01
    1.000000e+00
    1.326313e-01
    1.000000e-01
#-------------------------------------------------------------------------------------------
#
#	SELF-GRAVITATING EFFECT
#	=======================
# 1. the critical frequency [Hz] and the critical harmonic degree, below which
#    the self-gravitating effect should be included
#-------------------------------------------------------------------------------------------
    0.000000e+00     0
#-------------------------------------------------------------------------------------------
#
#	WAVE TYPES
#	==========
# 1. selection (1/0 = yes/no) of speroidal modes (P-SV waves), selection of toroidal modes
#    (SH waves), minimum and maximum cutoff harmonic degrees
#    Note: if the near-field static displacement is desired, the minimum
#          cutoff harmonic degree should not be smaller than, e.g., 2000.
#-------------------------------------------------------------------------------------------
    1     1    0 25000
#-------------------------------------------------------------------------------------------
#	GREEN'S FUNCTION FILES
#	======================
# 1. number of discrete source depths, estimated radius of each source patch [km] and
#    directory for Green's functions
# 2. list of the source depths [km], the respective file names of the Green's
#    functions (spectra) and the switch number (0/1) (0 = do not calculate
#    this Green's function because it exists already, 1 = calculate or update
#    this Green's function. Note: update is required if any of the above
#    parameters is changed)
#-------------------------------------------------------------------------------------------
   1   9.500000e-01   '/home/matrix/my_beat_case/Alor_seismic/AlorEQ/SOCY_ak135_2.000Hz_0/qssp_green/'
      4.000000e+00 'TEMP_4km_0km' 1
#-------------------------------------------------------------------------------------------
#
#	MULTI-EVENT SOURCE PARAMETERS
#	=============================
# 1. number of discrete point sources and selection of the source data format
#    (1 or 2)
# 2. list of the multi-event sources
#    Format 1:
#    M-Unit   Mrr  Mtt  Mpp  Mrt  Mrp  Mtp  Lat   Lon   Depth  T_origin T_rise
#    [Nm]                                   [deg] [deg] [km]   [sec]    [sec]
#    Format 2:
#    Moment   Strike    Dip       Rake      Lat   Lon   Depth  T_origin T_rise
#    [Nm]     [deg]     [deg]     [deg]     [deg] [deg] [km]   [sec]    [sec]
#-------------------------------------------------------------------------------------------
  1     1
   1.000000e+00    1.000000e+00    1.000000e+00    1.000000e+00    0.000000e+00    0.000000e+00    0.000000e+00    8.999999e+01    0.000000e+00    1.000000e+01    0.000000e+00    5.000000e-04
#-------------------------------------------------------------------------------------------
#
#	RECEIVER PARAMETERS
#	===================
# 1. output file name and and selection of output format:
#       1 = cartesian: vertical(z)/north(n)/east(e);
#       2 = spherical: radial(r)/theta(t)/phi(p)
#      (Note: if output format 2 is selected, the epicenter (T_origin = 0)
# 2. output time window [sec] (<= Green's function time window)
# 3. selection of order of Butterworth bandpass filter (if <= 0, then no
#    filtering), lower and upper corner frequencies (smaller than the cut-off
#    frequency defined above)
# 4. lower and upper slowness cut-off [s/km] (slowness band-pass filter)
# 5. number of receiver
# 6. list of the station parameters
#    Format:
#    Lat     Lon    Name     Time_reduction
#    [deg]   [deg]           [sec]
#    (Note: Time_reduction = start time of the time window)
#-------------------------------------------------------------------------------------------
  'receivers'  1
  7.385000e+02
  0 1.000000 1.000000
  0.000000e+00    1.326313e-01
  1
   1.664765e+01    1.800000e+02 '' 6.240000e+02
#-------------------------------------------------------------------------------------------
#
#	                LAYERED EARTH MODEL (IASP91)
#                   ============================
# 1. number of data lines of the layered model and selection for including
#    the physical dispersion according Kamamori & Anderson (1977)
#-------------------------------------------------------------------------------------------
    47    0
#-------------------------------------------------------------------------------------------
#
#	MULTILAYERED MODEL PARAMETERS (source site)
#	===========================================
# no depth[km] vp[km/s] vs[km/s] ro[g/cm^3]      qp     qs
#-------------------------------------------------------------------------------------------
1 0.000000e+00 2.200000e+00 1.100000e+00 2.200000e+00 5.000000e+01 5.000000e+01
2 3.340000e-01 2.200000e+00 1.100000e+00 2.200000e+00 5.000000e+01 5.000000e+01
3 3.340000e-01 5.000000e+00 2.500000e+00 2.600000e+00 6.000000e+02 4.000000e+02
4 3.034000e+00 5.000000e+00 2.500000e+00 2.600000e+00 6.000000e+02 4.000000e+02
5 3.034000e+00 6.600000e+00 3.650000e+00 2.900000e+00 1.471000e+03 6.000000e+02
6 6.334000e+00 6.600000e+00 3.650000e+00 2.900000e+00 1.471000e+03 6.000000e+02
7 6.334000e+00 7.100000e+00 3.900000e+00 3.050000e+00 1.491000e+03 6.000000e+02
8 1.329000e+01 7.100000e+00 3.900000e+00 3.050000e+00 1.491000e+03 6.000000e+02
9 1.329000e+01 8.036000e+00 4.486000e+00 3.638000e+00 9.497000e+02 3.946000e+02
10 8.000000e+01 8.040000e+00 4.481000e+00 3.500000e+00 1.008000e+03 4.176000e+02
11 8.000000e+01 8.045000e+00 4.490000e+00 3.502000e+00 1.820000e+02 7.560000e+01
12 1.200000e+02 8.050000e+00 4.500000e+00 3.427000e+00 1.826000e+02 7.606000e+01
13 1.200000e+02 8.050000e+00 4.500000e+00 3.427000e+00 1.826000e+02 7.606000e+01
14 1.650000e+02 8.175000e+00 4.509000e+00 3.371000e+00 1.887000e+02 7.655000e+01
15 2.100000e+02 8.301000e+00 4.518000e+00 3.324000e+00 2.010000e+02 7.940000e+01
16 2.100000e+02 8.300000e+00 4.519000e+00 3.323000e+00 3.382000e+02 1.337000e+02
17 3.000000e+02 8.628000e+00 4.679000e+00 3.401000e+00 3.536000e+02 1.387000e+02
18 4.100000e+02 9.030000e+00 4.870000e+00 3.506000e+00 3.775000e+02 1.465000e+02
19 4.100000e+02 9.360000e+00 5.080000e+00 3.929000e+00 4.141000e+02 1.627000e+02
20 6.600000e+02 1.020000e+01 5.611000e+00 3.918000e+00 4.285000e+02 1.729000e+02
21 6.600000e+02 1.079000e+01 5.965000e+00 4.240000e+00 1.349000e+03 5.495000e+02
22 7.640000e+02 1.107000e+01 6.215000e+00 4.359000e+00 1.276000e+03 5.371000e+02
23 8.491000e+02 1.121000e+01 6.272000e+00 4.463000e+00 1.263000e+03 5.273000e+02
24 1.038000e+03 1.152000e+01 6.407000e+00 4.616000e+00 1.230000e+03 5.069000e+02
25 1.227000e+03 1.181000e+01 6.527000e+00 4.710000e+00 1.198000e+03 4.880000e+02
26 1.416000e+03 1.208000e+01 6.636000e+00 4.812000e+00 1.168000e+03 4.704000e+02
27 1.605000e+03 1.233000e+01 6.735000e+00 4.909000e+00 1.141000e+03 4.544000e+02
28 1.795000e+03 1.255000e+01 6.827000e+00 5.004000e+00 1.111000e+03 4.377000e+02
29 1.984000e+03 1.278000e+01 6.913000e+00 5.096000e+00 1.065000e+03 4.156000e+02
30 2.173000e+03 1.300000e+01 6.997000e+00 5.186000e+00 1.037000e+03 4.006000e+02
31 2.362000e+03 1.321000e+01 7.079000e+00 5.273000e+00 9.954000e+02 3.812000e+02
32 2.551000e+03 1.343000e+01 7.162000e+00 5.357000e+00 9.681000e+02 3.673000e+02
33 2.740000e+03 1.365000e+01 7.248000e+00 5.439000e+00 9.325000e+02 3.506000e+02
34 2.740000e+03 1.365000e+01 7.248000e+00 5.693000e+00 7.227000e+02 2.717000e+02
35 2.790000e+03 1.365000e+01 7.259000e+00 5.720000e+00 7.269000e+02 2.740000e+02
36 2.839000e+03 1.366000e+01 7.270000e+00 5.746000e+00 7.251000e+02 2.740000e+02
37 2.892000e+03 1.366000e+01 7.282000e+00 5.772000e+00 7.231000e+02 2.740000e+02
38 2.892000e+03 7.972000e+00 0.000000e+00 9.928000e+00 5.782000e+04 0.000000e+00
39 3.344000e+03 8.744000e+00 0.000000e+00 1.059000e+01 5.782000e+04 0.000000e+00
40 3.797000e+03 9.338000e+00 0.000000e+00 1.112000e+01 5.782000e+04 0.000000e+00
41 4.249000e+03 9.759000e+00 0.000000e+00 1.155000e+01 5.782000e+04 0.000000e+00
42 4.702000e+03 1.009000e+01 0.000000e+00 1.188000e+01 5.782000e+04 0.000000e+00
43 5.154000e+03 1.032000e+01 0.000000e+00 1.214000e+01 5.782000e+04 0.000000e+00
44 5.154000e+03 1.104000e+01 3.505000e+00 1.270000e+01 6.328000e+02 8.503000e+01
45 5.397000e+03 1.112000e+01 3.567000e+00 1.282000e+01 6.192000e+02 8.503000e+01
46 5.884000e+03 1.123000e+01 3.647000e+00 1.297000e+01 6.050000e+02 8.503000e+01
47 6.370999e+03 1.127000e+01 3.672000e+00 1.302000e+01 6.006000e+02 8.503000e+01
#---------------------------------end of all inputs-----------------------------------------
===== end qssp input =====
===== begin qssp output =====
===== end qssp output =====
===== begin qssp error =====
===== end qssp error =====
qssp had a non-zero exit state: -11
qssp has been invoked as "fomosto_qssp2010"

I don't know what went wrong. Can you give me some suggestions?

**Comment by hvasbath** [comment]
It crashed without an error message. I had this before when I was short on memory. Please make sure your computer has enough memory free and try running again.

**Comment by vic-chou** [comment]
Hi, thanks for your reply. I can run sucessfully based on your suggestions.
