### ISSUE TITLE
Config Inconsistency and data import

### ISSUE THREAD

**Issue by LiliyaMalovichko** [hvasbath/beat#52]

**Comment by hvasbath** [comment]
issue resolved?

**Comment by LiliyaMalovichko** [comment]
Hi Hannes
 
thank you so much for your reply
I had to remove the settings for surface waves
- !beat.WaveformFitConfig
  include: true
  name: slowest
  blacklist: []
  channels: [Z]
  filterer: !beat.heart.Filter
    lower_corner: 0.001
    upper_corner: 0.1
    order: 4
  distances: [30.0, 90.0]
  interpolation: multilinear
  arrival_taper: !beat.heart.ArrivalTaper
    a: -15.0
    b: -10.0
    c: 50.0
    d: 55.0
King regards,
Liliya
 
>Пятница, 17 апреля 2020, 17:31 +10:00 от Hannes Vasyura-Bathke <notifications@github.com>:
> 
>issue resolved?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Liliya Malovichko

**Comment by hvasbath** [comment]
If you dont need the surface waves you can do that. But if you want to model them you need to include it. If you get the ConfigNeedsUpdatingError please follow the error message and update the config ;) .
How to is also described here: https://hvasbath.github.io/beat/getting_started.html#how-to-update-the-configuration-files

**Comment by LiliyaMalovichko** [comment]
thank you!   
>Пятница, 17 апреля 2020, 19:06 +10:00 от Hannes Vasyura-Bathke <notifications@github.com>:
> 
> 
>If you dont need the surface waves you can do that. But if you want to model them you need to include it. If you get the ConfigNeedsUpdatingError please follow the error message and update the config ;) .
>How to is also described here:  https://hvasbath.github.io/beat/getting_started.html#how-to-update-the-configuration-files
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Liliya Malovichko

**Comment by LiliyaMalovichko** [comment]
Hi Hannes
  Do you have an example of using pickle.py to create .pkl from .mseed, by any chance ? 
I’d like to explore the solution space of a Full Moment Tensor using real data is in .mseed
 
Cheers,
Liliya
  
>Пятница, 17 апреля 2020, 20:04 +10:00 от Liliya Malovichko <liramal@mail.ru>:
> 
>thank you!  
>>Пятница, 17 апреля 2020, 19:06 +10:00 от Hannes Vasyura-Bathke < notifications@github.com >:
>> 
>> 
>>If you dont need the surface waves you can do that. But if you want to model them you need to include it. If you get the ConfigNeedsUpdatingError please follow the error message and update the config ;) .
>>How to is also described here:  https://hvasbath.github.io/beat/getting_started.html#how-to-update-the-configuration-files
>>—
>>You are receiving this because you authored the thread.
>>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
> 
> 
>--
>Liliya Malovichko
>  
 
 
--
Liliya Malovichko

**Comment by hvasbath** [comment]
Hello Liliya,

please see here: https://hvasbath.github.io/beat/getting_started.html#seismic-data
You can follow either option. Please let me know if you need more instruction or if it does not work- then I will have to work on the explanation.

Best regards!
Hannes

**Comment by LiliyaMalovichko** [comment]
Hi, Hannes
I’m working with data from local seismic observation (underground mine) in proprietary format
I’ve exported data to .mseed or other option I can export just in ascii
I’ve started to modify beatdown.py (good luck to me :-) and I might have a questions regarding beatdown
Thank you!
  
>Четверг, 23 апреля 2020, 19:36 +10:00 от Hannes Vasyura-Bathke <notifications@github.com>:
> 
> 
>Hello Liliya,
>please see here:  https://hvasbath.github.io/beat/getting_started.html#seismic-data
>You can follow either option. Please let me know if you need more instruction or if it does not work- then I will have to work on the explanation.
>Best regards!
>Hannes
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Liliya Malovichko

**Comment by hvasbath** [comment]
Hi Liliya,

yes, please join the chat @braunfuss  mentioned I am online there several hours every day to answer questions. We set it up exactly for that purpose.
If you want to local mseed data through beatdown (in theory) you dont need to edit anything. You can use the options "local-data" and "local-responses-pz" or "local-responses-resp" for pole zero format or the IRIS resp format. Optionally you could also give a stationxml with "local-responses-stationxml".
Just put all your mseed files in one folder and the responses in another folder and give the pathes to the options.- It assumes raw data format- so if you restituted already it wont work. 
An example command string:
```
beatdown projectname '2017-04-13 16:22:16' 300 0.01 5 ula --local-responses-pz=/path/to/responses --local-data=/path/to/data --sites=
```

"sites" needs to be made empty otherwise it will start querrying data from the online catalogs.

Good luck!

**Comment by LiliyaMalovichko** [comment]
Thank you, that will help a lot
  
>Четверг, 23 апреля 2020, 23:09 +10:00 от Andreas Steinberg <notifications@github.com>:
> 
> 
>Hello Liliya,
>you also invited to use the support chat in mattermost for questions in a less formal environment:
>https://hive.pyrocko.org/pyrocko-support/channels/beat
>best,
>Andreas
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Liliya Malovichko

**Comment by LiliyaMalovichko** [comment]
Thank you Hannes,
I was able to convert test.mseed to .pkl using:
 
logger = logging.getLogger('')
traces = io.load('test.mseed')
traces_beat = []
for tr in traces:
    tr_beat = heart.SeismicDataset.from_pyrocko_trace(tr)
    traces_beat.append(tr_beat)
stations = model.load_stations('stations.txt')
utility.dump_objects(
    op.join('.', 'seismic_data_l.pkl'),
    outlist=[stations, traces_beat])
logger.info('prepared waveforms from %i stations' % len(stations))
 
and was able to visualize.
I’ll try to use option ‘local-data’
Will let you know in chat if it’ll work
 
Cheers
Liliya
  
>Пятница, 24 апреля 2020, 18:23 +10:00 от Hannes Vasyura-Bathke <notifications@github.com>:
> 
> 
>Hi Liliya,
>yes, please join the chat  @braunfuss mentioned I am online there several hours every day to answer questions. We set it up exactly for that purpose.
>If you want to local mseed data through beatdown (in theory) you dont need to edit anything. You can use the options "local-data" and "local-responses-pz" or "local-responses-resp" for pole zero format or the IRIS resp format. Optionally you could also give a stationxml with "local-responses-stationxml".
>Just put all your mseed files in one folder and the responses in another folder and give the pathes to the options.- It assumes raw data format- so if you restituted already it wont work.
>An example command string:
>beatdown projectname '2017-04-13 16:22:16' 300 0.01 5 ula --local-responses-pz=/path/to/responses --local-data=/path/to/data --sites=
>
>"sites" needs to be made empty otherwise it will start querrying data from the online catalogs.
>Good luck!
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Liliya Malovichko
