### ISSUE TITLE
Error: get_unit(): Bad internal unit KIND

### ISSUE THREAD

**Issue by rzinke** [hvasbath/beat#59]
I am working through the BEAT tutorial Example 3: Rectangular source. This time, I am using a Linux server (CentOS Linux 7).
 
I installed BEAT using the Anaconda installation method. Since I don't have super user privileges, I installed fomosto-psgrn-pscmp and fomosto-qssp with ```./configure --prefix=/u/sarh0/rzinke/local``` and added ```/u/sarh0/rzinke/local/bin``` to my PATH. 

I made it part way through Example 3. I successfully built the Green's functions for the geodetic data, but then for the seismic data I am getting an error. 

```
$ beat build_gfs Laquila --datatypes='seismic' --execute
```
yields:
```
pyrocko.fomosto.qssp - INFO     Starting step 1 / 2, block 1 / 8
pyrocko.fomosto.qssp - INFO     Starting step 1 / 2, block 2 / 8
pyrocko.fomosto.qssp - INFO     Starting step 1 / 2, block 3 / 8
pyrocko.fomosto.qssp - INFO     Starting step 1 / 2, block 4 / 8
pyrocko.fomosto.qssp - WARNING  qssp emitted something via stderr: 

At line 72 of file qpgetinp.f
Internal Error: get_unit(): Bad internal unit KIND

pyrocko.fomosto.qssp - WARNING  qssp emitted something via stderr: 

At line 72 of file qpgetinp.f
Internal Error: get_unit(): Bad internal unit KIND

pyrocko.fomosto.qssp - WARNING  qssp emitted something via stderr: 

At line 72 of file qpgetinp.f
Internal Error: get_unit(): Bad internal unit KIND

Traceback (most recent call last):
  File "/u/sar-r0/rzinke/python/miniconda3/envs/beat/bin/beat", line 33, in <module>
    sys.exit(load_entry_point('beat==1.0', 'console_scripts', 'beat')())
  File "/u/sar-r0/rzinke/python/miniconda3/envs/beat/lib/python3.6/site-packages/beat-1.0-py3.6-linux-x86_64.egg/beat/apps/beat.py", line 1686, in main
    globals()['command_' + command](args)
  File "/u/sar-r0/rzinke/python/miniconda3/envs/beat/lib/python3.6/site-packages/beat-1.0-py3.6-linux-x86_64.egg/beat/apps/beat.py", line 1038, in command_build_gfs
    force=options.force)
  File "/u/sar-r0/rzinke/python/miniconda3/envs/beat/lib/python3.6/site-packages/beat-1.0-py3.6-linux-x86_64.egg/beat/heart.py", line 1709, in seis_construct_gf
    store_dir, nworkers=sf.nworkers, force=force)
  File "/u/sar-r0/rzinke/python/miniconda3/envs/beat/lib/python3.6/site-packages/pyrocko/fomosto/qssp.py", line 1141, in build
    step=step, iblock=iblock)
  File "/u/sar-r0/rzinke/python/miniconda3/envs/beat/lib/python3.6/site-packages/pyrocko/gf/builder.py", line 165, in build
    Interrupted, store.StoreError)):
  File "/u/sar-r0/rzinke/python/miniconda3/envs/beat/lib/python3.6/site-packages/pyrocko/parimap.py", line 139, in parimap
    raise exc
pyrocko.fomosto.qssp.QSSPError: ===== begin qssp input =====
```

The full output is longer, but it ends with 
```
At line 72 of file qpgetinp.f
Internal Error: get_unit(): Bad internal unit KIND
```
Is this a Fortran compiler issue?

**Comment by hvasbath** [comment]
Oh my. Its an QSSP issue, not sure if this can result from compiling- because it seemed to have been compiled to the point you can run it at least. Never have seen that before.
Pinging @emolch.
Link to the QSSP issues where this belongs: https://git.pyrocko.org/pyrocko/fomosto-qssp/issues

**Comment by rzinke** [comment]
Hi @hvasbath, I am happy to help any way I can. How can I get the compilation log?
Is it
```
beat build_gfs Laquila --datatypes='seismic' --execute >log.txt
```

**Comment by hvasbath** [comment]
No. When you do the make in the fomosto-qssp program after ./configure .

**Comment by rzinke** [comment]
Ah, thanks. Here is the log.
[QSSP_log.txt](https://github.com/hvasbath/beat/files/5203270/QSSP_log.txt)

**Comment by hvasbath** [comment]
This looks ok- thats really puzzling.

**Comment by zyupcqingdao** [comment]
I have encountered the same problem, how can I solve it?

**Comment by hvasbath** [comment]
We do not have the slightest clue for now- help into investigating this would be welcome

**Comment by zyupcqingdao** [comment]
I may have solved the problem, but the reason should be that the versions of g++, gfortran, and gcc are different.













At 2023-03-24 17:15:21, "Hannes Vasyura-Bathke" ***@***.***> wrote:

We do not have the slightest clue for now- help into investigating this would be welcome

**Comment by hvasbath** [comment]
That would make sense.

**Comment by zyupcqingdao** [comment]
OK，thank you very much.
















在 2023-03-25 01:14:46，"Hannes Vasyura-Bathke" ***@***.***> 写道：

That would make sense.
