### ISSUE TITLE
How to obtain the model resolution matrix in beat

### ISSUE THREAD

**Issue by ranneylxr** [hvasbath/beat#78]
Hi again,
Does beat have the function that can show the model resolution matrix? If it does, could you please tell me the method to get it?
Thank you very much!
Best regards,

**Comment by hvasbath** [comment]
Hi,
unfortunately, not yet you will need to implement that yourself. If you do so please consider sharing it such that we can extend the software ...
Cheers!
Hannes

**Comment by ranneylxr** [comment]
OK! Thank you!
