### ISSUE TITLE
Could it be possible to set the azimuth angle for patch_resolution 3D geometry plot?

### ISSUE THREAD

**Issue by ranneylxr** [hvasbath/beat#96]
Hi again,
Thank you for providing the resolution distribution inversion method! I tried it by following the tutorial and got the path_resolution figure for my case.
But because the fault settings are a curve fault with a sub-horizontal decollement fault beneath it, plotting with the default azimuth, the figure cannot show the decollement fault clearly [Please see the attachment, the decollement fault was hiden by the curve fault]. 
Therefore, I check the `'-h'` for `'beat plot'` function, but I don't find the introduction about how to changing the azimuth angle.
I checked the `plotting.py` script but I don't think changing the `azim` parameters in `plotting.py` and rerunning is a good idea... In my case, the `beat build_gfs` will cost 2 hours to get the trade-off curve and the corresponding patch_resolution figures...
Could you please give me some suggestions?
Thank you very much!
Best regards,
Xiaoran.
![image](https://user-images.githubusercontent.com/35222932/149726281-7ec140db-382b-4cb5-9592-24ec6bceabe3.png)

**Comment by hvasbath** [comment]
Dear Xiaoran,
thank you for your message! For now there is no external attribute to access the azimuth angle, it is now defined to be perpendicular to the mean strike of all subfaults. However, you can indirectly still change it through the beat check option (mentioned in the tutorial under the manual fault selection section):
```
beat check Laquila_resolution --mode=ffi --what=discretization
```
This brings up the 3d interactive version of that static plot you have shown and you can rotate zoom and drag it to the position of your liking and then you can export it to the fileformat of your choice through the "save as" button. Please let me know if that solution is acceptable for you?! If not for sure we can figure sth out.

Cheers!
Hannes

**Comment by ranneylxr** [comment]
Dear Hannes,
I know what I did wrong... I didn't open the Xming so I didn't get any response when I ran the `beat check` command. 
Now the `beat check` command works well.
Thank you very much!
Best regards,
Xiaoran.

**Comment by hvasbath** [comment]
I am glad it works now!
