### ISSUE TITLE
Question about beat --help

### ISSUE THREAD

**Issue by WangJunyi2022** [hvasbath/beat#99]
Hello,
    I used Anaconda3 to install beat following the installation tutorial. After the installation is complete, beat init-help is used to test, and the following results appear. How can I solve this problem?

(base) gmtsar-user@gmtsarVB: conda activate beat
(beat) gmtsar-user@gmtsarVB:~$ beat init -h
usage: beat [-h] [-c] [-t TIME] [-z TZ] [-v]

optional arguments:
  -h, --help            show this help message and exit
  -c, --centibeats      Display centibeats
  -t TIME, --time TIME  Time to convert (HH:MM:SS)
  -z TZ, --timezone TZ  Timezone in hours, default: UTC+01
  -v, --version
(beat) gmtsar-user@gmtsarVB:
(beat) gmtsar-user@gmtsarVB:  beat init -help
usage: beat [-h] [-c] [-t TIME] [-z TZ] [-v]
beat: error: argument -h/--help: ignored explicit argument 'elp'
(beat) gmtsar-user@gmtsarVB:
(beat) gmtsar-user@gmtsarVB: beat init -h
usage: beat [-h] [-c] [-t TIME] [-z TZ] [-v]

optional arguments:
  -h, --help            show this help message and exit
  -c, --centibeats      Display centibeats
  -t TIME, --time TIME  Time to convert (HH:MM:SS)
  -z TZ, --timezone TZ  Timezone in hours, default: UTC+01
  -v, --version
(beat) gmtsar-user@gmtsarVB:~$

**Comment by hvasbath** [comment]
please either use beat init -h, or beat init --help

**Comment by WangJunyi2022** [comment]
Thank you!
